server:
  port: 8081
spring:
  batch:
    job:
      # 스케줄러에서 실행할 때는 자동 실행 방지
      name: ${job.name:NONE}
      enabled: false # 애플리케이션 시작 시 자동 실행 방지
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/netplix?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    database: mysql
    show-sql: true
  config:
    import:
      - "classpath:adapter-http-property.yml"
      - "classpath:adapter-persistence-property.yml"
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9a316d2c8c256cd791204a9eb006f7af
            client-secret: DTDbRT1xfv3mWLe1k3Lnshs4fOgXGp5u
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 7e0b9479f72ce9dd31b6c8c661bb047b2dcfc324d81b78de870959a38826f712
  expire:
    access-token: 3
    refresh-token: 24
